### ISSUE TITLE
Eslint fails to lint

### ISSUE THREAD

**Issue by eidellev** [apexskier/nova-eslint#358]
Hi! 

I've just started using Nova and can't seem to get ESlint to work.

**To reproduce**
It's a completely fresh install. I just open a TSX file, but see no ESLint errors or warnings.

**Environment**

- Nova version: 10.6
- Extension version: 1.7.3
- ESLint version: 8.30.0
- macOS version: 13.1
- NodeJS information:
  - node version: 18.12.0
  - npm version: 8.19.2
  - installation method: nvm

**Extension console output**
```
  stderr:  
Oops! Something went wrong! :(

ESLint: 8.30.0

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/lev/Projects/zencity/organic-frontend/node_modules/@eslint/eslintrc/universal.js
require() of ES modules is not supported.
require() of /Users/lev/Projects/zencity/organic-frontend/node_modules/@eslint/eslintrc/universal.js from /Users/lev/Projects/zencity/organic-frontend/node_modules/eslint/lib/linter/linter.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename universal.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/lev/Projects/zencity/organic-frontend/node_modules/@eslint/eslintrc/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/lev/Projects/zencity/organic-frontend/node_modules/eslint/lib/linter/linter.js:27:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```

**Comment by eidellev** [comment]
Turns out I had an old version of Node set as the default in `nvm`. Once I changed it to the current LTS version things started working as expected.
